name: accountcat-e2e
services:
  database:
    image: docker.io/postgres:17.5
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 2s
      retries: 5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: accountcat
  server:
    ports:
      - 3000:3000
    image: $IMAGE
    environment:
      DATABASE_HOST: database
      GOOGLE_LOGIN_CLIENT_ID: e2e-dummy
      HASHIDS_SALT: e2e-dummy
    command:
      - /opt/accountcat/accountcat
      - server
      - -a
