# WARNING: following settings are for demo purpose.
# It will create a postgresql database that trust all incoming connection, even ones without a password
# This is meant to running in a trusted network
name: accountcat-demo
services:
  database:
    image: docker.io/postgres:17.5
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 2s
      retries: 5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: accountcat
  database-init:
    build:
      context: .
      dockerfile: ./accountcat-server/Containerfile
    environment:
      DATABASE_HOST: database
      GOOGLE_LOGIN_CLIENT_ID: dummy
      HASHIDS_SALT: dummy
    depends_on:
      database:
        condition: service_healthy
    command:
      - ./accountcat
      - migrate
  server:
    ports:
      - 8080:3000
    build:
      context: .
      dockerfile: ./accountcat-server/Containerfile
    environment:
      DATABASE_HOST: database
volumes:
  database-data:

