# WARNING: following settings are for local development.
# It will create a postgresql database that trust all incoming connection, even ones without a password
# This is meant to running in a secure development environment
services:
  database:
    image: docker.io/postgres:17.5
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  database-data:

