[package]
name = "build_manifest"
version = "0.1.0"
edition = "2024"

[dependencies]
base16ct = "0.3.0"
clap = { version = "4.5.47", features = ["derive"] }
image = "0.25.8"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sha2 = "0.10.9"
