name: Build container image

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
    tags: v*

env:
  IMAGE: ghcr.io/${{ github.repository }}/server

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=edge
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: setup-buildx
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
            mirrors = ["mirror.gcr.io"]
      - name: Cache cache-mount
        uses: actions/cache@v4
        id: cache
        with:
          path: cache-mount
          key: cache-mount-${{ hashFiles('accountcat-server/Containerfile') }}
      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: cache-mount
          dockerfile: accountcat-server/Containerfile
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: accountcat-server/Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  trigger-demo-deploy:
    runs-on: ubuntu-latest
    needs: ['build-and-push-image']
    if: github.ref == 'refs/heads/main'
    environment:
      name: demo
      url: https://accountcat-demo.onrender.com/
    steps:
      - name: Call deploy hook
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

