name: Playwright Tests
on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup e2e server
      env:
        IMAGE: ghcr.io/${{ github.repository }}/server:${{ inputs.image-tag }}
      run: docker compose -f compose.e2e.yaml up -d
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      working-directory: ui
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ui
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ui
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
