name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/docker/library/rust:1-bookworm
    services:
      database:
        image: public.ecr.aws/docker/library/postgres:17.5
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: accountcat
    steps:
    - uses: actions/checkout@v4
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create server.toml
      run: mv accountcat-server/server.test.toml accountcat-server/server.toml
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
