name: Ui

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install node modules
      working-directory: ui
      run: npm install
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Install protoc-gen-js
      run: npm install -g protoc-gen-js
    - name: Generate gRPC-web files
      working-directory: ui
      run: make proto
    - name: Lint by biome
      working-directory: ui
      run: npx biome ci
    - name: Build
      working-directory: ui
      run: make

